### ISSUE TITLE
Ipfs error

### ISSUE THREAD

**Issue by yinyishun** [ipfs-shipyard/ipfs-desktop#1186]
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.9.1
- **Electron Version**: 6.0.7
- **Chrome Version**: 76.0.3809.139

**Error**

```
Error: net::ERR_CONNECTION_RESET
```

**Comment by humm0** [comment]
I think I was trying to Enable ipfs-npm but I was not able to. Sent from Mail for Windows 10 From: yinyishunSent: Tuesday, October 8, 2019 10:56 PMTo: ipfs-shipyard/ipfs-desktopCc: SubscribedSubject: [ipfs-shipyard/ipfs-desktop] Ipfs error (#1186) Please describe what you were doing when this error happened.SpecificationsOS: win32IPFS Desktop Version: 0.9.1Electron Version: 6.0.7Chrome Version: 76.0.3809.139ErrorError: net::ERR_CONNECTION_RESET—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by hacdias** [comment]
Close in favor of #1267
