### ISSUE TITLE
error when check update

### ISSUE THREAD

**Issue by devzyf** [ipfs-shipyard/ipfs-desktop#1608]
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: darwin
- **IPFS Desktop Version**: 0.12.2
- **Electron Version**: 8.2.5
- **Chrome Version**: 80.0.3987.165

**Error**

```
TypeError: ctx.checkForUpdates is not a function
    at click (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/src/tray.js:198:30)
    at MenuItem.click (electron/js2c/browser_init.js:1501:9)
    at Function.executeCommand (electron/js2c/browser_init.js:1762:13)
```

**Comment by jessicaschilling** [comment]
Thank you for bringing this to our attention! It's been flagged for review at the next weekly triage meeting.

**Comment by AbakumovAlexandr** [comment]
Not sure if it's due to the same issue - let me know if I'd have to create a separate one.

- > IPFS Desktop Version: 0.13.2
- > OS: Windows 10

I'm getting an error when going to `right click on the tray icon` -> `About` -> `Check for updates`:

![image](https://user-images.githubusercontent.com/6968009/109038492-cad59180-7699-11eb-94b1-fddee5f37bae.png)

I actually have Internet on my computer, so it's not a real cause.

**Comment by lidel** [comment]
@AbakumovAlexandr  Those are separate issues. Please fill a separate one (and write down if you installed as a single user of for all users).

**Comment by lidel** [comment]
@devzyf please reopen if you still experience the  issue described in https://github.com/ipfs-shipyard/ipfs-desktop/issues/1608#issue-679875055 with the latest version (0.14.0)
