### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ywl125** [ipfs-shipyard/ipfs-desktop#1609]
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.9.0
- **Electron Version**: 6.0.7
- **Chrome Version**: 76.0.3809.139

**Error**

```
Error: net::ERR_CONNECTION_RESET
```

**Comment by jessicaschilling** [comment]
When you get the chance, @lidel or @rafaelramalho19, can you please take a look? Thank you!

**Comment by lidel** [comment]
@ywl125 would need more logs to provide meaningful help, but on the surface it looks like you are running old version and it was not able to reach API, perhaps node did not start correctly?

:point_right: Please upgrade to IPFS Desktop [v0.12.2](https://github.com/ipfs-shipyard/ipfs-desktop/releases/tag/v0.12.2) and reopen if the issue is still there.
