### ISSUE TITLE
Automatic upgrade unpins the app from Windows taskbar

### ISSUE THREAD

**Issue by bertrandfalguiere** [ipfs-shipyard/ipfs-desktop#1770]
- OS: Windws 10 Pro
 - Version of IPFS Desktop update from 0.13.2 to 0.14.0

**Describe the bug**
I pinned the IPFS-Desktop to the Windows taskbar at the bottom for easy access:
![image](https://user-images.githubusercontent.com/8818223/108983745-762d1900-768f-11eb-862a-a31b9c0cc24b.png)

When upgrading to 0.14.0, the shortcut was removed from the taskbar. 

Using the desktop shortcut :

![image](https://user-images.githubusercontent.com/8818223/108984137-e2a81800-768f-11eb-85d3-ced6cdfbaacb.png) 

or the launching the app from the Windows search menu :

![image](https://user-images.githubusercontent.com/8818223/108984398-29960d80-7690-11eb-9f8f-89546529b71b.png)
 both works fine.

Pinning again the shortcut to the taskbar works fine.

**To Reproduce**
1. Have IPFS-Desktop 0.13.2 installed on Windows.
2. Pin the icon to task bar
3. Wait for automatic upgrade to notify you of the downloaded v0.14.0
4. Close IPFS-Desktop
5. Windows asks if you are OK to trust IPFS-Desktop to upgrade
6. Accept
7. The IPFS-Desktop icon is now unpinned from taskbar

**Expected behavior**
The IPFS Desktop icon is still pinned to Windows taskbar.

**Screenshots**
![image](https://user-images.githubusercontent.com/8818223/108984922-bd67d980-7690-11eb-8db1-991a517b84bc.png)

**Logs**

[error.log](https://github.com/ipfs-shipyard/ipfs-desktop/files/6035143/error.log)
[combined.log](https://github.com/ipfs-shipyard/ipfs-desktop/files/6035144/combined.log)

**Comment by lidel** [comment]
This is an upstream bug either in electron (we updated from 9.x to 11.x) or electron-builder (because of its track record). 

Based on  https://github.com/signalapp/Signal-Desktop/issues/2529, https://github.com/electron-userland/electron-builder/issues/2514, https://github.com/electron-userland/electron-builder/pull/5312 I assume this was fixed  in electron-builder, and future releases should not unpin.

Feel free to reopen if this happens in >0.14.0.
