### ISSUE TITLE
Make it i18n friendly

### ISSUE THREAD

**Issue by daviddias** [ipfs-shipyard/ipfs-desktop#650]
@satazor implemented this for js.ipfs.io using react-intl and it is super easy to work with. @satazor, wanna shine some light here?

**Comment by satazor** [comment]
Yes we used [react-intl](https://github.com/yahoo/react-intl) in js.ipfs.io, mainly because it's made for react and supports:

- messages with placeholders
- date & time
- relative dates (xxx ago)
- number formatting, including currency

The strategy we went for was to have a [intl](https://github.com/ipfs/js.ipfs.io/tree/master/intl) folder that container everything related to i18n. Contributors just need to follow a few steps to add a new language, which are detailed in the README.

Note that ideally, you would lazy load the locale files. More specifically, you should only call [addLocaleData](https://github.com/yahoo/react-intl/wiki/API#addlocaledata) when a language is requested.

I think that's all, feel free to ask more questions and I will happily provide help.

**Comment by lidel** [comment]
cc https://github.com/ipfs/ipfs-gui/issues/50

**Comment by lidel** [comment]
Some relevant notes: https://github.com/ipfs/i18n#adding-i18n-to-your-project
I think we won't have a lot of string in revamped version.
As soon initial UI lands,  may be a good idea to prioritize i18n and do it sooner than later, that way translation team will have more time to work on it before shipping :)

**Comment by hacdias** [comment]
I can add it on the PR I'm working on. It's not that much 😄

**Comment by lidel** [comment]
@hacdias as long the change set is not too big. 

(Would be cool to have it in separate PR, so we can link to it as an example for other projects that want to add i18n)

**Comment by hacdias** [comment]
@lidel it would probably introduce a lot of changes to the code I wrote so far, but basically just adding translation functions. We can leave it for another PR just to keep things separated. #662 is already getting really big, but it couldn't be other way since it introduces really deep changes.
