### ISSUE TITLE
Binary signing for macOS

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs-shipyard/ipfs-desktop#66]

**Comment by Dignifiedquire** [comment]
@jbenet how long do you think this will take you? Is it realistic to get this done for 1.0?

**Comment by jbenet** [comment]
i'm not sure. i'll look into it, but this week is basically shot for me. if you need it this week, then no. next week is likely. then there's apple's review process. i think it's much faster now, but it used to take a week or something.

**Comment by Dignifiedquire** [comment]
That's fine, I'll do the prerelease unsigned this week and want to wait at least one week anyway before the real release.

**Comment by Dignifiedquire** [comment]
Ref https://github.com/maxogden/electron-packager/issues/163

**Comment by olizilla** [comment]
Happy to say we're getting a first pass on "signed releases for macOS" in to the next release, in significantly less than 4 years after the initial proposal.

Of note, it is tricky. There are a bunch of hoops you have to jump through on the Apple Developer portal and more on the local keychain handling, and more again to wire it up to CI.

- You need to be the Apple Developer "Team Agent" to create certificates. 
- There can be only one Team Agent,  having the admin role wont do.
- You must have 2 factor auth enabled on your apple ID.
- You must create certificate signing request via the Keychain Access app to create certificates.
- You must create both a `Developer Installer` and a `Developer Application` certifcate, and download them to your local keychain.
- You have to access them via the "My Certificates" filter, to enable the "export as .p12" option. If you navigate to them via another filter or search, that export option is not available. You better be the team agent if you want that to work. If all the planets are aligned you should be able to export them as a combined, encrypted `.p12` file like so

![add-apple-certs](https://user-images.githubusercontent.com/58871/51535890-b0d57f00-1e41-11e9-8f2d-b2d959016e25.gif)

Then follow the steps in https://www.electron.build/code-signing#travis-appveyor-and-other-ci-servers to wire it up for CI

> To sign app on build server you need to set CSC_LINK, CSC_KEY_PASSWORD:
- Export certificate. Consider to not use special characters (for bash) in the password because “values are not escaped when your builds are executed”.
- Encode file to base64 (macOS: `base64 -i yourFile.p12 -o envValue.txt`, Linux: `base64 yourFile.p12 > envValue.txt`).

Thanks to @jesseclay for sticking with me on this advenure!

**Comment by olizilla** [comment]
I figured this out from a mix of
- https://www.electron.build/code-signing
- https://medium.com/@jondot/shipping-electron-apps-to-mac-app-store-with-electron-builder-e960d46148ec
- fumbling in the dark

**Comment by hacdias** [comment]
Binary signing is set up and working. The next version will have macOS signed binaries.
