### ISSUE TITLE
Submit to Flathub.org for Flatpak

### ISSUE THREAD

**Issue by Mikaela** [ipfs-shipyard/ipfs-desktop#686]
* https://github.com/flathub/flathub/wiki/App-Submission

Flatpak is popular universal (on Linux) package manager for GUI apps and I would like to see IPFS GUI there to try it as I am not sure on installing app without being sure that it will get updates like the other installed apps.

Reading the issue tracker, you already have something Flatpak related, but I don't see an issue explicitly requesting support for it. https://github.com/ipfs-shipyard/ipfs-desktop/issues?q=flatpak

**Comment by hacdias** [comment]
Closing in favour of #691.

**Comment by petesimonic** [comment]
should this one be reopened since #691 is closed, 
but Flatpak still missing, and there is no active issue to reflect this

> Closing in favour of #691.

**Comment by Winterhuman** [comment]
@hacdias Any update on this? I realise it's been a while, but it seems petesimonic's comment is still relevant

**Comment by DeedleFake** [comment]
I was quite disappointed to find this issue seemingly abandoned. I use the AUR package for IPFS Desktop, but it's had problems a few times because of poor Node versioning support. A Flatpak doesn't have that problem, so it would be really nice to be able to install IPFS Desktop via Flathub and not worry about it anymore.
