### ISSUE TITLE
Allow devs to try out beta versions before we make a general release

### ISSUE THREAD

**Issue by olizilla** [ipfs-shipyard/ipfs-desktop#938]
Let's use the release channels feature of electron-builder. https://www.electron.build/tutorials/release-using-channels

It'd be great if I could toggle a setting in the app, to opt-in to recieving beta updates.

In the app config we could opt-ing in to alpha updates.

**Comment by olizilla** [comment]
To start making use of this after the next release, we'd set the package version in master to be `0.9.0-alpha`. When we were ready to test out a release, we'd set it to `0.9.0-beta`, and then release by setting it to `0.9.0`. 

- We need to make  it so we can configure `autoUpdater.channel` at run time.
- It should always default ot `latest` aka "stable". 
- minimum viable: make it so I can opt in to beta or alpha release by updating a property in the desktop config file.

**Comment by olizilla** [comment]
@hacdias wait a minute... the main goal here is to be able to publish release candidates without having everyone auto-update to that version... i was just re-reading the docs  https://www.electron.build/tutorials/release-using-channels

> By default (without using channels), all application releases use the “latest” channel.

>"latest”, your application is stable and this is the default one (example: 1.3.2)

So I am assuming that if we don't do  anything, we can publish 0.8.0-rc.1 and existing installs *will not* auto-update to that version.

Is that your understanding? We could test that out today...

It's important that the auto-update only pulls stable releases. It's far less important that devs have a way to auto-update beta releases right now, as we can publish them and ask friendly testers to download them manually.

**Comment by hacdias** [comment]
@olizilla by reading the documentation, yes, it seems that if we publish `0.8.r-rc.1`, it won't be installed automatically.

Although, we have the option `allowPrerelease` enabled (https://www.electron.build/auto-update.html) because we're not marking any releases as actual releases on GitHub releases. I know those are different things, but I wonder if they are related somehow.

And yes, we can certainly release an 0.8.0-rc.1 today to try it out.

**Comment by olizilla** [comment]
> `allowPrerelease` Defaults to true if application version contains prerelease components (e.g. 0.12.1-alpha.1, here alpha is a prerelease component), otherwise false.

I take that to mean that it'll download pre-releases updates if the user currently has a pre-release. that seems like a reasonable default.

**Comment by hacdias** [comment]
@olizilla that is for GitHub releases. We have it set to `true` because all our releases are marked as pre-releases.

**Comment by olizilla** [comment]
oh noes! if we explicitly set it to true, then everyone gets the alpha releases. From reading the docs, it looks like it only cares about the version string, not the github release "pre-release" flag.  Do you recall  why you set it  to true in the  first place? Did you see an issue with auto-update not fetching "stable versions like 0.7.0 because the release was fagged as pre-release?

**Comment by hacdias** [comment]
@olizilla yes, that's the reason we set it to true. And it makes sense to be related to flagging as pre-releases because it is a `GitHub provider only` feature.

**Comment by hacdias** [comment]
@olizilla just releases 0.8.0-rc.1 and 0.7.3 detects it as an update. What I suggest:

1. Let `allowPrerelease` use the defaults.
2. Release 0.8.0-rc.2.
3. See if 0.8.0-rc.1. **It should.**
4. Release 0.8.0.

Although this misses one big important point: we're not testing if now the stable finds the rc or not... We could, perhaps, unrelease 0.8.0-rc.1 and release 0.7.4 and try it out.

**Comment by hacdias** [comment]
Wait! We're using `latest` channel too for our releases. Even for pre-releases. Perhaps we could:

- Enable channels (https://www.electron.build/tutorials/release-using-channels#electron-builder), then pre-releases would stay on a different channel.
- Keep `allowPrerelease` on `true`. This **is** related to our flagging on GitHub prereleases. If let it default, a user on latest channel won't be able to upgrade to a beta version even if they choose to because it won't find versions marked as pre-releases.

After enabling channels:

- release 0.7.4
- see if 0.7.3 updates to 0.7.4
- Release 0.8.0-rc.1. Check if 0.7.4 does not upgrade.
- Release 0.8.0.

Or use 0.8.0 and 0.8.1 instead of 0.7.4.

**Comment by olizilla** [comment]
@hacdias as i understand it `latest` is supposed to mean `stable`, and the default for `allowPrerelease` is supposed to mean that folks with a stable release will only update to the next stable release, while folks with a beta releast would update to either the next beta or the next stable release. That sounds good.

**Comment by olizilla** [comment]
So it turns out that release channels are **not a thing** when using electron-builder with github, which we only discovered by going through the electron-builder source. huzzah.

To avoid deplyed apps from auto-updating, we enable the pre-release flag on the github release. When we are happy with them, we create a release with the pre-release flag disabled. electron-builder ignores all other signals for auto-updating via github.
